### ISSUE TITLE
Keeps Showing Warning - "Trailing whitespace | KvLint(I002)" 

### ISSUE THREAD

**Issue by ghost** [Monk3yDev/kvlang-vscode#13]
- Issue Type: `Bug`
- Extension Name: `KvLang`
- Extension Version: `0.0.6`
- OS Version: `macOS Big Sur 11.5`
- VSCode Version: `1.57.1`
- Python Version: `3.9.5`

**[Issue]**
Keeps showing `Trailing whitespace | KvLint(I002)` warning.
Using sample code provided by [Kivy Documentation ](https://kivy.org/doc/stable/tutorials/pong.html)

<img width="812" alt="Screen Shot 2021-06-21 at 1 46 58 AM" src="https://user-images.githubusercontent.com/60351865/122682116-91b9c200-d232-11eb-89ec-6af29ed15310.png">

**Comment by Monk3yDev** [comment]
![image](https://user-images.githubusercontent.com/8431461/122943937-b9ff0900-d377-11eb-9d77-5aa00e17fb07.png)
Because text from the site contains whitespaces. LS only detects it so it is not a bug.
