### ISSUE TITLE
Update to support Python 3.9

### ISSUE THREAD

**Issue by benetherington** [Monk3yDev/kvlang-vscode#9]
[What's New In Python 3.9](https://docs.python.org/3/whatsnew/3.9.html):
> The encoding parameter of json.loads() has been removed. As of Python 3.1, it was deprecated and ignored; using it has emitted a DeprecationWarning since Python 3.8. (Contributed by Inada Naoki in [bpo-39377](https://bugs.python.org/issue39377))

Because server\kvls\message.py:65 still uses the encoding argument in release 0.0.5, the VSCode language server now crashes when running in Python 3.9.

**Comment by benetherington** [comment]
Oh! Apologies, this is already fixed!

Closing the issue. This is just waiting on the next release to the VSC extensions library. I'll run the pre-release code instead.

**Comment by Monk3yDev** [comment]
I was not tracking Python updates at all. I will remove encoding param from the json.loads()

**Comment by Monk3yDev** [comment]
Version 0.0.6 should not crash because of encoding parameter in json.loads().
